Repository pinterest/pinterest-python-sdk, pull requests merged in 2022-12, with the labels that each got.

#27 Release version 0.2.0
  pinterest/ads/ad_accounts.py
  pinterest/ads/ad_groups.py
  pinterest/ads/ads.py
  pinterest/ads/audiences.py
  pinterest/ads/campaigns.py
  pinterest/ads/customer_lists.py
  pinterest/ads/keywords.py
  pinterest/client/__init__.py
  pinterest/organic/boards.py
  pinterest/organic/pins.py
  pinterest/utils/base_model.py
  pinterest/utils/bookmark.py
  tests/src/pinterest/ads/test_ad_accounts.py
  tests/src/pinterest/ads/test_ad_groups.py
  tests/src/pinterest/ads/test_ads.py
  tests/src/pinterest/ads/test_audiences.py
  tests/src/pinterest/ads/test_campaigns.py
  tests/src/pinterest/ads/test_customer_lists.py
  tests/src/pinterest/ads/test_keywords.py
  tests/src/pinterest/bin/get_config_test.py
  tests/src/pinterest/client/client_test.py
  tests/src/pinterest/client/test_pinterest_client.py
  tests/src/pinterest/organic/test_boards.py
  tests/src/pinterest/organic/test_pins.py
  tests/src/pinterest/utils/__init__.py
  tests/src/pinterest/utils/test_load_json_config.py
  tests/test-requirements.txt
Labels: release

#30 feat(ci): add integration test
  .github/workflows/integrationtests.yml
  Makefile
  integration_tests/__init__.py
  integration_tests/ads/__init__.py
  integration_tests/ads/test_ad_accounts.py
  integration_tests/ads/test_ad_groups.py
  integration_tests/ads/test_ads.py
  integration_tests/ads/test_audiences.py
  integration_tests/ads/test_campaigns.py
  integration_tests/ads/test_customer_lists.py
  integration_tests/ads/test_keywords.py
  integration_tests/base_test.py
  integration_tests/client/test_client.py
  integration_tests/config.py
  integration_tests/organic/test_boards.py
  integration_tests/organic/test_pins.py
  integration_tests/test_pinterest_base_model.py
  integration_tests/utils/ads_utils.py
  integration_tests/utils/organic_utils.py
Labels: enhancement

#36 Add documentation generator - `lazydocs`
  dev-requirements.txt
  docs/utils/README.md
  docs/utils/python-sdk-doc.yaml
  docs/utils/script.py
  docs/utils/skeleton-spec.yaml
Labels: feature

#34 Analytics base model outline and fields
  .pylintrc
  pinterest/utils/analytics.py
  pinterest/utils/validations.py
Labels: feature

#38 Add overview file and update script
  docs/utils/script.py
Labels: feature

#39 Update script logic
  docs/utils/script.py
Labels: feature-branch

#41 Generate documentation using script.py
  README.md
  docs/pinterest/.pages
  docs/pinterest/README.md
  docs/pinterest/ads.ad_accounts.md
  docs/pinterest/ads.ad_groups.md
  docs/pinterest/ads.ads.md
  docs/pinterest/ads.audiences.md
  docs/pinterest/ads.campaigns.md
  docs/pinterest/ads.customer_lists.md
  docs/pinterest/ads.keywords.md
  docs/pinterest/ads.md
  docs/pinterest/bin.get_config.md
  docs/pinterest/bin.md
  docs/pinterest/client.md
  docs/pinterest/config.md
  docs/pinterest/organic.boards.md
  docs/pinterest/organic.md
  docs/pinterest/organic.pins.md
  docs/pinterest/utils.base_model.md
  docs/pinterest/utils.bookmark.md
  docs/pinterest/utils.error_handling.md
  docs/pinterest/utils.load_json_config.md
  docs/pinterest/utils.md
  docs/pinterest/utils.refresh_access_token.md
  docs/pinterest/utils.sdk_exceptions.md
  docs/pinterest/version.md
  docs/utils/python-sdk-doc.yaml
  docs/utils/script.py
Labels: feature

#40 Ad Account `get_analytics`
  pinterest/ads/ad_accounts.py
  pinterest/utils/analytics.py
Labels: feature
